config/routes.rb
Rails.application.routes.draw do
  get 'passwords/new'

  get 'passwords/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#new'


  get '/profil', to: 'users#edit', as: :profil
  patch '/profil', to: 'users#update'


  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy', as: :destroy_session

  resources :passwords, only: [:new, :create, :update, :edit]

  resources :users, only: [:new, :create] do
    member do
      get 'confirm'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_secure_token :confirmation_token
  has_secure_token :recover_password

  validates :username,
            format: {with: /\A[a-zA-Z0-9_]{2,20}\z/, message: 'Ne doit contenir que des caractères alphanumérique ou des _'},
            uniqueness: {case_sensitive: false}

  validates :email,
            uniqueness: {case_sensitive: false}



  def to_session
    {id: id}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



  protect_from_forgery with: :exception

  before_action :only_signed_in

  add_flash_types :success, :danger

  helper_method :current_user, :user_signed_in?

  private
  def only_signed_in
    if !user_signed_in?
      redirect_to new_user_path, danger: "Vous n'aver pas le droit d'accéder a cette page"
    end
  end

  def current_user
    return nil if !session[:auth] || !session[:auth]['id']
    return @_user if @_user
    @_user = User.find_by_id(session[:auth]['id'])
  end

  def user_signed_in?
    !current_user.nil?
  end

  def only_signed_out
    redirect_to profil_path if user_signed_in?
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController

  skip_before_action :only_signed_in
  before_action :only_signed_out

  def new

  end

  def create

    @user = User.find_by_email(user_params[:email])

    if @user
      @user.regenerate_recover_password
      UserMailer.password(@user).deliver_now
      redirect_to new_session_path, success: 'Un email vous a été envoyé'
    else
      redirect_to new_passwords_path, danger: 'Aucun utilisateur ne correspond a cet email'
    end
  end

  def edit
    @user = User.find(params[:id])

    if @user.recover_password == params[:token]
    else
      redirect_to new_password_path, danger: 'Le token invalide'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.recover_password == user_params[:recover_password]
      @user.assign_attributes(user_params)
      if @user.valid?
        @user.recover_password = nil
        @user.save
        session[:auth] = @user.to_session
        redirect_to profil_path, success: 'Mot de passe modifer'
      end
    else
      render 'edit'
    end
  end

  private

  def user_params
    user_params = params.require(:user).permit(:password, :password_confirmation, :recover_password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :only_signed_in, only: [:new, :create]
  before_action :only_signed_out, only: [:new, :create]

  def new
  end

  def create
    user_params = params.require(:user)
    @user = User.where(username: user_params[:username]).or(User.where(email: user_params[:username])).first

    if @user and @user.authenticate(user_params[:password])
      session[:auth] = @user.to_session
      redirect_to profil_path, success: "Vous êtes connecter"
    else
      redirect_to new_session_path, danger: "Identification incorrect"
    end

  end

  def destroy
    session.destroy
    redirect_to new_session_path, success: "Vous êtes maintenant déconnecter"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :only_signed_in, only: [:new, :create, :confirm]

  before_action :only_signed_out, only: [:new, :create, :confirm]
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:username, :email, :password, :password_confirmation)
    @user = User.new(user_params)
    @user.recover_password = nil

    if @user.valid?
      @user.save
      UserMailer.confirm(@user).deliver_now
      redirect_to new_user_url, success: 'Vous devrez recevoir un mail de confirmation'
    else
      render 'new'
    end
  end

  def confirm
    @user = User.find(params[:id])
    if @user.confirmation_token == params[:token]
      @user.update_attributes(confirmed: true, confirmation_token: nil)
      @user.save(validate: false)
      session[:auth] = @user.to_session
      redirect_to profil_path, success: 'OK'
    else
      redirect_to new_user_path, danger: 'Ce token ne semble pas valide'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    user_params = params.require(:user).permit(:username, :firstname, :lastname, :email)

    if @user.update(user_params)
      redirect_to profil_path, success: "Votre compte a bien été mise à jours"
    else
      render 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gestion</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <a href="<%= root_path %>" class="navbar-brand">TEST</a>
        </div>
        <div class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdow-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                <%= current_user.username %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Mon profil', profil_path %></li>
                <li><%= link_to 'Se deconnecter', destroy_session_path, data: {method: :delete} %></li>
              </ul>
            </li>
          <% else %>
            <li><a href="<%= new_user_path %>">S'inscrire</a></li>
            <li><a href="<%= new_session_path %>">Se connecter</a></li>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <% if flash[:success] %>
          <div class="alert alert-success">
            <%= flash[:success] %>
          </div>
      <% end %>
      <% if flash[:danger] %>
          <div class="alert alert-danger">
            <%= flash[:danger] %>
          </div>
      <% end %>
      <%= yield %>
      <%= debug session[:auth] %>
    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>


<div class="panel panel-default">
  <div class="panel-heading">Modifier mon profil</div>
  <div class="panel-body">
    <%= form_for @user, url: profil_path, html: {class: 'form-horizontal'} do |f| %>

        <div class="form-group">
          <%= f.label :username, "Pseudo de l'utilisateur", class: 'col-md-4 control-label' %>
          <div class="col-md-6">
            <%= f.text_field :username, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :email, "Email", class: 'col-md-4 control-label' %>
          <div class="col-md-6">
            <%= f.email_field :email, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :firstname, "Prenom de l'utilisateur", class: 'col-md-4 control-label' %>
          <div class="col-md-6">
            <%= f.text_field :firstname, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :lastname, "Nom de l'utilisateur", class: 'col-md-4 control-label' %>
          <div class="col-md-6">
            <%= f.text_field :lastname, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-md-6 col-md-offset-4">
            <button type="submit" class="btn btn-primary">Editer</button>
          </div>
        </div>

    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class="panel panel-default">
  <div class="panel-heading">S'inscrire</div>
    <div class="panel-body">
      <%= form_for @user, html: {class: 'form-horizontal'} do |f| %>

        <div class="form-group">
          <%= f.label :username, "Nom de l'utilisateur", class: 'col-md-4 control-label' %>
          <div class="col-md-6">
            <%= f.text_field :username, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :email, "Email", class: 'col-md-4 control-label' %>
          <div class="col-md-6">
            <%= f.email_field :email, class: 'form-control' %>
          </div>
        </div>


        <div class="form-group">
          <%= f.label :password, "Mot de passe", class: 'col-md-4 control-label' %>
          <div class="col-md-6">
            <%= f.password_field :password, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation, "Confirmation du mot de passe", class: 'col-md-4 control-label' %>
          <div class="col-md-6">
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
        </div>

          <div class="form-group">
            <div class="col-md-6 col-md-offset-4">
              <button type="submit" class="btn btn-primary">S'incrire</button>
            </div>
          </div>

      <% end %>
  </div>
</div>